newrelic:
  policy: Fulfiller Integration Squad policy
  refreshrate: 10000
  
gitlab:
  groupId: 121
  groupIds:
    - 121
    - 338
    - 169
  refreshrate: 10000

slideshow:
  youtube:
    - xJAc07JROGg #train
    - m9VO7X_q9nw #kittens!
    - 9vlavTW0rn4 #bison
    - GfgwU-pyOfg #africa
  rate: 120000
