newrelic:
  policy: Fulfiller Integration Squad policy
  refreshrate: 10000

slideshow:
  youtube:    
    - 7U7ijVPuZ3Q #kittens
    - -CpDQ6BT5mk #puppies!
    - kBsp75gXFZo #jellyfish
  twitch:
    - cgntv_
    - waltertheplatypus
  rate: 120000
