newrelic:
  policy: Fulfiller Integration Squad policy
  refreshrate: 10000
  
gitlab:
  groupId: 121
  groupIds:
    - 121
    - 338
    - 169
  refreshrate: 10000

slideshow:
  youtube:    
    - FEiOjdr9Nz4 #Fish
    - -CpDQ6BT5mk #puppies!
    - 9vlavTW0rn4 #bison
    - GfgwU-pyOfg #africa
  rate: 120000
