newrelic:
  policy: Fulfiller Integration Squad policy
  refreshrate: 10000

slideshow:
  youtube:
    - 7U7ijVPuZ3Q #kittens
    - kBsp75gXFZo #jellyfish
    - Lq3iH0tedtA #breath of the wild
  rate: 120000
